---
# tasks file for kube-wordpress

- name: Copying Kube Wordpress files 
  copy: 
   src: "K8s-WordPress"
   dest: "/home/ubuntu" 

- name: Copying Kube Storage Class file
  template:
    src: "storage.yml.j2"
    dest: "/home/ubuntu/K8s-WordPress/storage.yml"
    
# - name: Deploying Wordpress on Kubernetes
#   command: kubectl create -k /home/ubuntu/K8s-WordPress/

# - name: Go to this below URL to access WordPress after few seconds
#   debug:
#     msg: http://{{ groups['ec2_master'][0] }}:31000
# tasks file for kube-wordpress   

# - name: Copying Kube Wordpress files 
#   copy: 
#    src: "K8s-WordPress"
#    dest: "/ubuntu" 

# - name: Copying Kube Storage Class file
#   template:
#     src: "storage.yml.j2"
#     dest: "/ubuntu/K8s-WordPress/storage.yml"

# - name: Apply PersistentVolume
#   k8s:
#     state: present
#     definition: "/ubuntu/K8s-WordPress/storage.yml"

# apt install python3-pip -y
# pip3 install kubernetes

# - name: Deploy Nginx Ingress 
#   shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/aws/deploy.yaml

    
# - name: Deploying Wordpress on Kubernetes
#   command: kubectl create -k /home/ubuntu/K8s-WordPress/

# - name: Go to this below URL to access WordPress after few seconds
#   debug:
#     msg: http://{{ groups['ec2_master'][0] }}:31000

# http://44.214.16.19:31000