kind: Service
apiVersion: v1
metadata:
  name: my-service
  namespace: my-namespace
spec:
  selector:
    app:  nginx
  # type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - protocol: TCP
    port:  80
    targetPort:  80