pipeline {
    agent any
    environment {
        KEY = credentials('KEY')
    }
    stages {

        stage('Clean') {
            steps {
                cleanWs()
            }
        }
        stage('clone') {
            steps {
                echo "Clonage du repo en cour..."
                checkout scmGit(branches: [[name: '*/main']],
                 extensions: [],
                 userRemoteConfigs: [[url: "https://$KEY@github.com/Kameli71/Projet-nuage.git"]]
                 )
                sh('pwd && ls -la')
            }
        }
        stage('Build instances') {
            steps {
                echo 'Installation des ec2 et autoscalling group'
                sh('export ANSIBLE_PRIVATE_KEY_FILE="karim-new-key.pem"')
                sh('export ANSIBLE_HOST_KEY_CHECKING=False')
                sh('chmod 400 karim-new-key.pem')
                sh('ansible-playbook ./ansible-kub/ec2-setup.yml')
                echo 'Installation des ec2 terminé !'
            }
        }
        stage('Build Nfs-server') {
            steps {
                echo 'Installation du Nfs-server'
                sh('ansible-playbook -i ./ansible/inventory/dynamic_inventory_aws_ec2.yaml ./ansible-kub/nfs-setup.yml')
                echo 'Installation des Nfs-server terminé !'
            }
        }      
        stage('Build Configuration') {
            steps {
                echo 'Configuration du cluster'
                sh("ansible-playbook -i ./ansible/inventory/dynamic_inventory_aws_ec2.yaml ./ansible-kub/roles/k8s_master/tasks/main.yml")
                echo 'Installation des ec2 terminé !'
            }
        }
        stage('Build Microservices') {
            steps {
                echo 'Installation du microservice'
                sh('ansible-playbook -i ./ansible/inventory/dynamic_inventory_aws_ec2.yaml ./ansible-kub/setup.yml')
                echo 'Installation des microservices terminé !'
            }
        }
    }
}
   