apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
      tier: cart
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: cart
        tier: cart
        track: stable
    spec:
      containers:
        - name: cart
          image: cart:latest
          env:
        - name : MONGO_URL
          value: mongodb+srv://karim:stargatesg71@clustercart.2roa2cs.mongodb.net/
          # Use secret in real usage
        - name: PORT
          value: 8000
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: cart-storage
              mountPath: /data
      volumes:
        - name: cart-storage
          persistentVolumeClaim:
            claimName: my-pv