apiVersion: v1
kind: Service
metadata:
  labels:
    name: cart
    visualize: "true"
  name: cart
spec:
  ports:
    - port: 8080
      targetPort: 8000
  selector:
    name: cart
  sessionAffinity: None
  type: NodePort