- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpcCidrBlock }}"
    region: "{{ region }}"
    dns_support: "yes"
    dns_hostnames: "yes"
    tenancy: "default"
    state: "{{ state }}"
    resource_tags:
      Name: "{{ vpc_name }}"
    register: vpc_result