---
- name: Configure Firewalld on Amazon Linux
  hosts: localhost
  become: yes  # Permet à Ansible d'exécuter des commandes avec sudo

  tasks:
    - name: Install firewalld (if not already installed)
      yum:
        name: firewalld
        state: present

    - name: Start firewalld
      service:
        name: firewalld
        state: started

    - name: Open port 8080/tcp
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
      become: yes

    - name: Open port 6443/tcp
      firewalld:
        port: 6443/tcp
        permanent: yes
        state: enabled
      become: yes
