- hosts: all
  # gather_facts: no
  gather_facts: no
  become: true

# - hosts: role_worker_nfs
#   become: true
#   tasks:
#     - name: Running NFS Server Role
#       include_role:
#         name: nfs-server
  # tasks:
  #   - name: Deployement micro cart
  #     include_role:
  #       name: cart
# - hosts: role_master
#   become: true
#   gather_facts: no
#   tasks:
#     - name: Running K8s Master Role
#       include_role:
#         name: k8s_master

- hosts: role_master
  become: true
  gather_facts: yes
  tasks:
    - debug: var=ansible_all_ipv4_addresses verbosity=0
    - name: Running K8s Slave Role
      include_role:
        name: kube-wordpress

# - hosts: role_master
#   become: true
#   gather_facts: no
#   tasks:
#     - name: Running K8s Slave Role
#       include_role:
#         name: node
