- hosts: all
  # become: yes
  # gather_facts: no
  gather_facts: no
  become: true

# - hosts: role_worker_nfs
#   become: true
#   tasks:
#     - name: Running NFS Server Role
#       include_role:
#         name: nfs-server

# - hosts: role_master
#   become: true
#   gather_facts: no
#   tasks:
#     - name: Running K8s Master Role
#       include_role:
#         name: k8s_master

# - hosts: role_worker
#   become: true
#   gather_facts: no
#   tasks:
#     - name: Running K8s Slave Role
#       include_role:
#         name: k8s_slave

- hosts: role_master
  become: true
  gather_facts: no
  tasks:
    - name: Running Kube WordPress Role
      include_role:
        name: kube-wordpress